### ISSUE TITLE
Recognize 'flat spot' in E-max waveform

### ISSUE THREAD

**Issue by flelmend** [GridProtectionAlliance/openXDA#2]
A common failure mode for some E-max DFRs it a flat spot in the waveform. The bad data detection logic for openXDA needs to be modified to identify and report on this issue. 
![e-max flat noname](https://cloud.githubusercontent.com/assets/13469543/15654015/bdad78e6-265e-11e6-888b-6fab1a8ed942.PNG)

**Comment by ritchiecarroll** [comment]
Moved to Slack for tracking
