### ISSUE TITLE
sql ending comment

### ISSUE THREAD

**Issue by maxwickPPL** [GridProtectionAlliance/openXDA#8]
openXDA.sql script is missing end comment */  ???  I am getting this on install.

**Comment by StephenCWills** [comment]
There are some multi-line comments with code in them.
https://github.com/GridProtectionAlliance/openXDA/blob/master/Source/Data/01%20-%20openXDA.sql#L1755

The code that executes scripts is too simple to navigate this comment correctly.
https://github.com/GridProtectionAlliance/gsf/blob/master/Source/Libraries/GSF.Core/Data/DataExtensions.cs#L924

The most obvious solution would be to use single-line comments instead, as is done at the top of the script.
https://github.com/GridProtectionAlliance/openXDA/blob/master/Source/Data/01%20-%20openXDA.sql#L8

**Comment by clackner-gpa** [comment]
This has been fixed in version `3.0.70`
